[package]
name = "thread_pool"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# a multi sender, multi receiver channel
crossbeam-channel = "0.5"
