name: Rust

on:
  push:
    branches: ["master"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov
      - name: Generate code coverage
        run: cargo llvm-cov test --all-features --workspace --lcov --output-path lcov.info
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
